# Generated by Django 3.0.7 on 2020-07-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrol',
            name='course',
            field=models.IntegerField(),
        ),
    ]
